#!/bin/bash
if [ $# -eq 0 ]; then
  flatpak run org.DolphinEmu.dolphin-emu -u /home/evanfox/Emulators2/dolphin/dolphin.config
else
  flatpak run org.DolphinEmu.dolphin-emu -u /home/evanfox/Emulators2/dolphin/dolphin.config -b -e "$1"
fi
